### PR TITLE
Adding additional node data metrics

### PR DESCRIPTION
**Pull request by shannonmitchell**

### CODE REVIEW

**Comment by shannonmitchell** [comment]
### Description of the changes

We need the ability to alert on how close we come to some node data metric limits. This change adds those metrics.

### PR Review Checklist

#### Author
- [ ] the PR should focus on a single subject. Change only relevant files to the problem you’re working on
Clean and format the code
- [ ] add unit tests for your changes and make sure all unit tests are passing
- [ ] add a risk label after carefully considering the "blast radius" of your changes
- [ ] describe the intent of your changes in the description. don't just rewrite your code in prose
- [ ] assign at least one reviewer
- [ ] address the feedback

#### Reviewer
- [ ] review code for readability
- [ ] verify that high risk behavior changes are well tested
- [ ] check license for any new external dependency
- [ ] ask questions about anything that isn't clear and obvious
- [ ] approve the PR when you consider it's good to merge

**Comment by shannonmitchell** [comment]
I'm new to this.  Doesn't look like I have permissions to set a label or request a reviewer.   Since we are just adding new metrics and leaving the existing ones alone, it should be low risk.

**Comment by camdencheek** [comment]
Hi @shannonmitchell -- thanks for the PR! I've assignmed myself as reviewer and I'll do a little validation in the next couple of days

**Review by camdencheek — APPROVED** [review]

**Comment by camdencheek** [comment]
LGTM -- thanks again for the contribution

**Pull request merged**
